//package com.app.exception;
//
//public class ExceptionEx7 {
//
//	public static void main(String[] args) {
//		try {
//			int arr[] = new int[10];
//			arr[5] = 30/0;
//		} catch (Exception e) {
//			System.out.println("Common Task Completed");
//		}catch (ArithmeticException e) {
//			System.out.println("Task1 is completed");
//		}catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("task2 is compledted");
//		}
//		System.out.println("Rest of the code...");
//	}
//}
